# Generated by Django 5.0.6 on 2024-06-14 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencebyyear',
            name='conference',
        ),
        migrations.AddField(
            model_name='conference',
            name='years',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conferences.conferencebyyear'),
        ),
    ]
