# Generated by Django 5.0.6 on 2024-06-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_remove_conferencebyyear_conference_conference_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencebyyear',
            name='conf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conferences.conference'),
            preserve_default=False,
        ),
    ]
