# Generated by Django 5.0.6 on 2024-06-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_conferencebyyear_conf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencebyyear',
            name='conf',
        ),
    ]
