# Generated by Django 5.0.6 on 2024-06-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_rename_school_conferencebyyear_schools_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencebyyear',
            old_name='conf',
            new_name='conference',
        ),
    ]
