# Generated by Django 5.0.6 on 2024-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0010_auto_20240617_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencename',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/conf_logos'),
        ),
    ]
