# Generated by Django 5.0.6 on 2024-06-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0011_conferencename_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/school_logos'),
        ),
    ]
