# Generated by Django 5.0.7 on 2024-07-22 20:47

from django.db import migrations
from DatabaseCreation.DistanceCalculator.distanceCalc import BigEastBuilder


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0014_auto_20240722_1944'),
    ]

    operations = [
        migrations.RunPython(BigEastBuilder)
    ]
