# Generated by Django 5.0.7 on 2024-07-22 21:48

from django.db import migrations
from DatabaseCreation.DistanceCalculator.distanceCalc import SWCBuilder, BigEightBuilder


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0015_auto_20240722_2047'),
    ]

    operations = [
        migrations.RunPython(SWCBuilder),
        migrations.RunPython(BigEightBuilder)
    ]
