# Generated by Django 5.0.7 on 2024-07-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0016_auto_20240722_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencename',
            name='historical',
            field=models.BooleanField(default=False),
        ),
    ]
