# Generated by Django 5.0.7 on 2024-07-25 20:37

from django.db import migrations
from DatabaseCreation.DistanceCalculator.distanceCalc import correctPac12DistanceBetweenSchools


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0018_auto_20240724_2042'),
    ]

    operations = [
        migrations.RunPython(correctPac12DistanceBetweenSchools),
    ]
    