# Generated by Django 5.0.7 on 2024-07-25 20:39

from django.db import migrations
from DatabaseCreation.DistanceCalculator.distanceCalc import correctPac12DistanceBetweenSchools


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0019_auto_20240725_2037'),
    ]

    operations = [
        migrations.RunPython(correctPac12DistanceBetweenSchools),
    ]
