# Generated by Django 5.0.7 on 2024-07-26 21:45

from django.db import migrations
from DatabaseCreation.DistanceCalculator.distanceCalc import correctMoreConferences


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0020_auto_20240725_2039'),
    ]

    operations = [
        migrations.RunPython(correctMoreConferences),
    ]
